services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres  # Replace with your username
      POSTGRES_PASSWORD: password  # Replace with a strong password
      POSTGRES_DB: chatdb  # Replace with your desired database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent data storage
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # Admin email
      PGADMIN_DEFAULT_PASSWORD: admin             # Admin password
    ports:
      - "5050:80"                            # Expose PgAdmin on port 5050
    depends_on:
      - postgres   

  redis-stack:
    image: redis/redis-stack:latest  # Use the Redis Stack image
    container_name: redis-stack
    ports:
      - "6379:6379"  # Expose Redis port
      - "8001:8001"  # Redis Stack includes a web UI for monitoring
    volumes:
      - redis-stack-data:/data

volumes:
  postgres_data:
    driver: local
  redis-stack-data:
    driver: local
